# Project
title:            Flywire Styleguide
description:      Common UI patterns used through Flywire apps

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _site
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              http://peertransfer.github.io/flystyles/
encoding:         UTF-8

# Data
collections:
  docs:
    output: false

# Assets
sass:
  sass_dir:          _scss
  style:            :compressed
