# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

title:            Flywire Styleguide
description:      Common UI patterns used through Flywire apps

# Server
source:           docs/src
destination:      docs/dist
host:             0.0.0.0
port:             9001
url:              http://flywire.com
encoding:         UTF-8

collections:
  docs:
    output: false
