# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           src
destination:      dist
host:             0.0.0.0
port:             9001
url:              http://flywire.com
encoding:         UTF-8

collections:
  docs:
    output: false
